#!/bin/sh
# Run this to generate all the initial makefiles, etc.

DIE=0

echo "Generating configuration files for wmcoincoin, please wait...."

echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING "
echo "you need autoconf-2.5x AND automake-1.6 to generate the makefiles ..."
echo "please check that autoconf --version give 2.5x and automake --version gives 1.6"
echo "you will also need a recent gettext (0.11.5 is fine)"
echo "à la main, le 0.10.40 marche aussi , mais pas 0.10.35"
echo 
echo 
echo 
echo 
echo 
echo 
echo "yes it sucks"
echo

(autoconf --version) < /dev/null > /dev/null 2>&1 || {
	echo
        echo "You must have autoconf installed to compile wmcoincoin."
        echo "Download the appropriate package for your distribution,"
        echo "or get the source tarball at ftp://ftp.gnu.org/pub/gnu/"
        DIE=1
}

(automake --version) < /dev/null > /dev/null 2>&1 || {
        echo
        echo "You must have automake installed to compile wmcoincoin."
        echo "Download the appropriate package for your distribution,"
        echo "or get the source tarball at ftp://ftp.gnu.org/pub/gnu/"
        DIE=1
}

if test "$DIE" -eq 1; then
        exit 1
fi

cp -p po/ChangeLog po/ChangeLog.save
./setup-gettext
mv po/ChangeLog.save po/ChangeLog

#cp po/Makefile.in.in intl/Makefile.in.in
echo "  aclocal -I m4 $ACLOCAL_FLAGS"
aclocal -I m4 $ACLOCAL_FLAGS
echo "  autoheader"
autoheader || exit;
if test ! -e m4/Makefile.am; then
  echo "cette grosse bouse de gettextize ne veut plus installer de Makefile.am dans le rép m4"
  echo "alors je vais le faire"
  s=`cd m4 && ls *.m4`;
  echo "#made by autogen.sh ..." > m4/Makefile.am
  echo "EXTRA_DIST = "$s >> m4/Makefile.am
fi;
echo "  automake --add-missing --gnu --include-deps"
automake --add-missing --gnu --include-deps
echo "  autoconf"
autoconf || exit;


if test -z "$*"; then
    echo "I am going to run ./configure with no arguments - if you wish "
    echo "to pass any to it, please specify them on the $0 command line."
    echo "If you do not wish to run ./configure, press Ctrl-C now."
    trap 'echo "configure aborted" ; exit 0' 1 2 15
    sleep 1
fi
./configure "$@"
