#!/bin/sh
#
#$VER: wmpanpan v0.02beta 
#
# wmpanpan, le script le plus con du monde, 
# qui sauve le monde et votre bureau de ce petit canard.
#
# Par DivC, au bureau, alors que son employeur compte sur lui pour
# un dossier urgent...
#
# Faut commenter les scipts on m'a dit, je commente...
#
# Ce script implemente une maniere totalement revolutionnaire pour
# quitter wmcoincoin. Il permet d'eviter "shutdown -h now".
# Il est en version beta, ne contient aucune detection d'erreur,
# et ne verifie meme pas si la chasse est ouverte. 
# Ce script est sous GPL, bien sur... Je refuse donc toute responsabilite
# si votre ordinateur est terrorise par les coups de feu, si le
# garde-chasse vient a passer, ou n'importe quoi d'autre...
#
# Pour faire joli:
#
echo "pan!"
#
# Ici, le noeud du probleme, le coeur du processus...
#
### killall wmcoincoin
### patch de fpy pour toujours plus de portabilité (et il tue aussi les wmcoincoin-kde) !
kill `ps -elf | grep wmcoincoin | grep -v grep | awk '{print $4}'`
# Pour faire joli aussi, et justifier le "panpan":
#
echo "pan!"
