fprintf(f,"###fichier d'options rcsid=$Id: defaultoptionsfile.h,v 1.5 2001/12/18 12:43:37 pouaite Exp $\n");
fprintf(f,"\n");
fprintf(f,"###vous pouvez décommenter des options et changer leur valeurs\n");
fprintf(f,"\n");
fprintf(f,"### delai enntre deux verifications de la tribune (en secondes)\n");
fprintf(f,"#tribune.delay: 30\n");
fprintf(f,"\n");
fprintf(f,"### nombre maximum de messages qui sont conservés en mémoire (et affichables dans le pinnipede\n");
fprintf(f,"### teletype). Ne lui donnez pas une valeur extravagante (genre 10000), wmcoincoin n'a pas été conçu pour ça !\n");
fprintf(f,"#tribune.max_messages: 400\n");
fprintf(f,"\n");
fprintf(f,"#tribune.troll_detector: off\n");
fprintf(f,"\n");
fprintf(f,"### les couleurs sont en héxadecimal ( '00000' = noir, 'ff0000' = rouge, '00ff00' = vert ...)\n");
fprintf(f,"\n");
fprintf(f,"#dock.bg_color: ffb12b\n");
fprintf(f,"#dock.bg_pixmap: /chemin/vers/un/fichier.xpm (de dimensions 64x64)\n");
fprintf(f,"### couleur du texte défilant\n");
fprintf(f,"#dock.fg_color: 000000\n");
fprintf(f,"\n");
fprintf(f,"### jouer sur les deux options suivantes pour faire fonctionner wmcoincoin avec d'autres\n");
fprintf(f,"### windowmanagers que WindowMaker (par exemple, sous kwm/KDE, il faut 'dock.iconwin: False')\n");
fprintf(f,"### (en ligne de commande, ce sont les options '-B' et -w')\n");
fprintf(f,"#dock.draw_border: False\n");
fprintf(f,"#dock.iconwin: True\n");
fprintf(f,"\n");
fprintf(f,"### ces petits ballons d'aide peuvent être casse-couilles\n");
fprintf(f,"#dock.use_balloons: True\n");
fprintf(f,"\n");
fprintf(f,"###\n");
fprintf(f,"dock.balloons.font_family: helvetica\n");
fprintf(f,"dock.balloons.font_size: 10\n");
fprintf(f,"\n");
fprintf(f,"### quand draw_border est activée, cette option permet de position la fenetre (format 'xpos:ypos')\n");
fprintf(f,"### (equivalent de l'option '-x'\n");
fprintf(f,"#dock.pos: 0:400\n");
fprintf(f,"\n");
fprintf(f,"\n");
fprintf(f,"### delai entre deux verifications des news, du flamometre, etc... (en secondes)\n");
fprintf(f,"#news.delay: 300\n");
fprintf(f,"\n");
fprintf(f,"### la fonte des news ... verdana en 11, c'est plus joli\n");
fprintf(f,"#news.font_family: helvetica\n");
fprintf(f,"#news.font_size: 12\n");
fprintf(f,"#news.bg_color: dae6e6\n");
fprintf(f,"#news.fg_color: 000000\n");
fprintf(f,"### position et dimensions de la fenêtre d'affichage des news\n");
fprintf(f,"#news.location: 100:200\n");
fprintf(f,"#news.dimensions: 600:300\n");
fprintf(f,"\n");
fprintf(f,"### ce nom apparaitra au début de tous vos posts\n");
fprintf(f,"#palmipede.username: plop\n");
fprintf(f,"### si il y a une occurenre de '$u', '$v', '$s', '$r' et/ou '$m', elles seront\n");
fprintf(f,"###  remplacés par les valeurs suivantes:\n");
fprintf(f,"###  $u -> votre username\n");
fprintf(f,"###  $v -> version du canard\n");
fprintf(f,"###  $s -> system name (Linux, ...)\n");
fprintf(f,"###  $r -> system release\n");
fprintf(f,"###  $m -> machine (i686,...)\n");
fprintf(f,"#palmipede.useragent: my name is $u and i love you\n");
fprintf(f,"#palmipede.default_message: je ne suis pas du tout d'accord avec toi\n");
fprintf(f,"\n");
fprintf(f,"\n");
fprintf(f,"### equivalent de l'option '-r' -> url de la page principale\n");
fprintf(f,"#http.site_url: http://linuxfr.org\n");
fprintf(f,"#http.path_tribune_backend: board/remote.xml\n");
fprintf(f,"#http.path_news_backend: backend.rdf\n");
fprintf(f,"#http.path_end_news_url: ,0,-1,6.html\n");
fprintf(f,"#http.path_tribune_add: board/add.php3\n");
fprintf(f,"#http.path_myposts: users/myposts.php3?order=id\n");
fprintf(f,"#http.path_messages: messages/\n");
fprintf(f,"\n");
fprintf(f,"#http.cookie: <inserez la valeur xxx du cookie 'session_id=xxx' de linuxfr ici>\n");
fprintf(f,"\n");
fprintf(f,"### si vous ne fournissez pas votre cookie, mais que vous voulez qd meme\n");
fprintf(f,"### voir des fortunes dans le pinnipede, utilisez cette option\n");
fprintf(f,"#http.force_fortune_retrieval: yes\n");
fprintf(f,"\n");
fprintf(f,"#http.proxy: proxy:port\n");
fprintf(f,"#http.proxy_auth: username:password\n");
fprintf(f,"\n");
fprintf(f,"### décommenter cette ligne si votre proxy a tendance à cacher comme un salaud\n");
fprintf(f,"#http.proxy_use_nocache: on\n");
fprintf(f,"\n");
fprintf(f,"# ## L'option 'http.browser' permet d'utiliser un navigateur externe, pour\n");
fprintf(f,"# ## lire les commentaires détecté par le flamophone, et pour afficher les [url] du\n");
fprintf(f,"# ## pinnipede teletype. on peut utiliser:\n");
fprintf(f,"# ## ATTENTION, ce genre de commande externe peut etre une source de vulnerabilité,\n");
fprintf(f,"# ## les caractères bizarres dans les urls sont escapés avant d'etre envoyés\n");
fprintf(f,"# ## au browser externe, mais si le browser est lui-même buggé...\n");
fprintf(f,"# ## Par défaut, aucun browser n'est sélectionné (ça peut rassurer les plus paranoiaques)\n");
fprintf(f,"# ## Le %%s est remplacé par l'url escapée, et la ligne de commande résultante est passée au shell\n");
fprintf(f,"\n");
fprintf(f,"#http.browser: opera %%s &\n");
fprintf(f,"#http.browser: galeon -n %%s &\n");
fprintf(f,"#http.browser: konqueror %%s &\n");
fprintf(f,"#http.browser: netscape %%s &\n");
fprintf(f,"#http.browser: mozilla %%s &\n");
fprintf(f,"\n");
fprintf(f,"### nouveau (v2.2beta) -> un deuxième browser, activable en cliquant avec le bouton\n");
fprintf(f,"### du milieu au lieu du bouton de gauche\n");
fprintf(f,"#http.browser2: xterm -fn 6x13 -bg white -fg black -geometry 120x80 -e w3m %%s &\n");
fprintf(f,"\n");
fprintf(f,"\n");
fprintf(f,"# ## par défaut le pinnipède est en helvetica, mais je trouve 'verdana' (en taille 11)\n");
fprintf(f,"# ## bien plus jolie. l'inconvenient, c'est qu'elle est plus lente a afficher...          \n");
fprintf(f,"# ## et qu'elle n'est pas dispo sur toutes les distribs\n");
fprintf(f,"\n");
fprintf(f,"#pinnipede.font_family: verdana\n");
fprintf(f,"#pinnipede.font_size: 11\n");
fprintf(f,"#pinnipede.bg_color: dae6e6\n");
fprintf(f,"#pinnipede.fg_color: 303030\n");
fprintf(f,"#pinnipede.clock_color: 004000\n");
fprintf(f,"#pinnipede.useragent_color: 800000\n");
fprintf(f,"#pinnipede.login_color: ffff00\n");
fprintf(f,"#pinnipede.url_color: 0000ff\n");
fprintf(f,"#pinnipede.trollscore_color:\n");
fprintf(f,"#pinnipede.button_color: dae6e6\n");
fprintf(f,"#pinnipede.emph_color: ffffff\n");
fprintf(f,"#pinnipede.fortune_bgcolor: b0b0b0\n");
fprintf(f,"#pinnipede.fortune_fgcolor: 000000\n");
fprintf(f,"#pinnipede.fortune_font_family: helvetica\n");
fprintf(f,"#pinnipede.fortune_font_size: 9\n");
fprintf(f,"\n");
fprintf(f,"### location du pinnipede (sous la forme 'xpos:ypos' )\n");
fprintf(f,"#pinnipede.location: 128:64\n");
fprintf(f,"### dimension du pinnipede, au format largeur:hauteur\n");
fprintf(f,"#pinnipede.dimensions: 300:455\n");
fprintf(f,"#pinnipede.buttons: off\n");
fprintf(f,"\n");
fprintf(f,"### les 5 options suivantes correspondent aux boutons\n");
fprintf(f,"### du pinnipede\n");
fprintf(f,"#pinnipede.show_tags: on\n");
fprintf(f,"#pinnipede.show_seconds: on\n");
fprintf(f,"\n");
fprintf(f,"### nick_mode-> 0: n'affiche rien, \n");
fprintf(f,"###\t\t1: affiche les useragent raccourcis, \n");
fprintf(f,"###     \t2: affiche les logins, \n");
fprintf(f,"###\t\t3: affiche les deux, \n");
fprintf(f,"###\t\t4: affiche useragent ou login\n");
fprintf(f,"#pinnipede.nick_mode: 4\n");
fprintf(f,"#pinnipede.show_troll_score: on\n");
fprintf(f,"#pinnipede.show_fortune: on\n");
fprintf(f,"\n");
fprintf(f,"### Options relatives au spell checker\n");
fprintf(f,"### Active/desactive le spellchecker\n");
fprintf(f,"#spell.enable: True\n");
fprintf(f,"### spell checker compatible ispell (ispell, aspell, ...)\n");
fprintf(f,"#spell.cmd: ispell\n");
fprintf(f,"### Dictionnaire associé (french, english ....)\n");
fprintf(f,"#spell.dict: french\n");
