fprintf(f,"#useragents.v1.3\n");
fprintf(f,"#syntaxe: forme[tab]couleur_hexa[tab]regexp[tab]nom[fin_de_ligne]\n");
fprintf(f,"#Utilisez bien des TABULATIONS pour separer les champs\n");
fprintf(f,"#les formes disponibles:\n");
fprintf(f,"#  ignore carre trou triangle trianglebas triangledroite trianglegauche croix plus slash antislash coin11 coin12 coin21 coin22\n");
fprintf(f,"#les couleurs son en hexedecimal (ff0000 -> rouge, 00ff00 -> vert, 0000ff ->bleu, ff8000 -> orange etc..\n");
fprintf(f,"#les regex sont case-sensitive -- man regex\n");
fprintf(f,"#le nom ne devrait pas faire plus de 9 caracteres (pour pouvoir etre affiché entierement)\n");
fprintf(f,"#\n");
fprintf(f,"# NOUVEAU: si le nom est '?', alors wmcoincoin déterminera le nom par rapport au useragent\n");
fprintf(f,"# en utilisant les premiers caractères du useragent\n");
fprintf(f,"#\n");
fprintf(f,"carre\t\tff6080\t\tMozilla/5.0 \\(X11; U; Linux 2.2.19 i686; en-US; m18\\) Gecko/20\tF.Penso?\n");
fprintf(f,"carre\t\t00d0a0\t\t.*Galeon.*\t\tGaleon\n");
fprintf(f,"carre\t\tffff00\t\twmCoinCoin/2.0 .*\tNOOOON!\n");
fprintf(f,"carre\t\tffff00\t\twmCoinCoin/2.[01].*\tvieuxcoin\n");
fprintf(f,"carre\t\t40ff20\t\t.*wm[cC]oin[cC]oin.*\twmc²\n");
fprintf(f,"carre\t\ta0a000\t\t.*[Tt]roll[Bb]rowser.*\tTBrowser\n");
fprintf(f,"carre\t\tffff00\t\t.*[Tt]ribune[Cc]lient.*\tTClient\n");
fprintf(f,"croix\t\t00ff00\t\t.*[Dd]ae.*\t\tDae\n");
fprintf(f,"croix\t\t4040ff\t\t.*[Kk]ad.*\t\tKadreg\n");
fprintf(f,"croix\t\t00ffff\t\tjr-lamoule\t\tJR\n");
fprintf(f,"carre\t\tff00ff\t\t.*OmniWeb.*\t\tMACOS X\n");
fprintf(f,"trianglegauche\tffff00\t\t.*Nautilus.*\t\tNautilus\n");
fprintf(f,"carre\t\tff0000\t\t.*MSIE 6.0; Windows NT 5.1.*\tIE6/WinXP\n");
fprintf(f,"losange\t\tf07010\t\tMozilla/5.0.*Linux.*\tMoz-Linux\n");
fprintf(f,"carre\t\tff0000\t\t.*Linux.*smp\t\tLinuxSMP\n");
fprintf(f,"trou\t\tffd0f0\t\t.*Linux.*2.2.17-21mdk.*\tMdk7.2\n");
fprintf(f,"trou\t\tfff080\t\t.*Linux 2\\.4\\.8\\-26mdk.*\tMdk8.1\n");
fprintf(f,"trou\t\tfff080\t\t.*Linux.*2.4.*mdk.*\tMdk8.x\n");
fprintf(f,"carre\t\tffd0f0\t\t.*Linux.*mdk.*\t\tMandrake\n");
fprintf(f,"carre\t\tffb040\t\t.*Linux 2.2.16-22.*\tRedHat7 ?\n");
fprintf(f,"carre\t\tff6000\t\t.*Linux.2.0.*\t\tLinux 2.0\n");
fprintf(f,"carre\t\tffd000\t\t.*Linux.2.2.*\t\tLinux 2.2\n");
fprintf(f,"carre\t\tffa000\t\t.*Linux.2.4.*\t\tLinux 2.4\n");
fprintf(f,"triangle\t40ff40\t\t.*Konqueror.*\t\tKonqueror\n");
fprintf(f,"losange\t\tc0c080\t\t.*PPC.*\t\t\tPPC\n");
fprintf(f,"losange\t\tc0c080\t\t.*ppc.*\t\t\tppc\n");
fprintf(f,"trianglebas\t1cffd9\t\t.*NetBSD.*\t\tNetBSD\n");
fprintf(f,"trianglebas\t1cefe9\t\t.*OpenBSD.*\t\tOpenBSD\n");
fprintf(f,"trianglebas\t1cdff9\t\t.*FreeBSD.*\t\tFreeBSD\n");
fprintf(f,"croix\t\tff0000\t\t.*BeOS.*\t\tmmu\n");
fprintf(f,"slash\t\t1cdff9\t\t.*MSIE.*Linux.*Opera.*\tOpera/Lnx\n");
fprintf(f,"slash\t\t1cdff9\t\t.*NT 4..*Opera.*\tOpera/NT4\n");
fprintf(f,"slash\t\t1cdff9\t\t.*MSIE.*Opera.*\t\tOpera\n");
fprintf(f,"slash\t\t1cdff9\t\t.*Opera.*\t\tOpera\n");
fprintf(f,"trianglegauche\t80c0bf\t\t.*MSIE 4.*NT.*\t\tIE4/NT\n");
fprintf(f,"trianglegauche\t60f05f\t\t.*MSIE 4.*dows 95.*\tIE4/w95\n");
fprintf(f,"triangle\t0ca8ff\t\t.*MSIE 5.*NT 5.0.*\tIE5/W2K\n");
fprintf(f,"triangle\t4000ff\t\t.*MSIE 5.*NT 4.0.*\tIE5/NT4\n");
fprintf(f,"triangle\t4000ff\t\t.*MSIE 5.*NT.*\t\tIE5/NT\n");
fprintf(f,"triangle\t50b06f\t\t.*MSIE 5.*dows 95.*\tIE5/w95\n");
fprintf(f,"triangle\t70c08f\t\t.*MSIE 5.*dows 98.*\tIE5/w98\n");
fprintf(f,"coin12\t\t2000ff\t\t.*MSIE 5.5.*\t\tMSIE 5.5\n");
fprintf(f,"coin22\t\t0000ff\t\t.*MSIE 6.0.*\t\tMSIE 6\n");
fprintf(f,"triangle\t0000ff\t\t.*MSIE.*\t\tMSIE\n");
fprintf(f,"trou\t\tf080f0\t\t.*HP-UX.*\t\tHP-UX\n");
fprintf(f,"trou\t\tf000f0\t\t.*SunOS.*\t\tSunOS\n");
fprintf(f,"trou\t\tf08080\t\t.*IRIX64.*\t\tIrix64\n");
fprintf(f,"trou\t\tff0000\t\t.*OSF.*alpha.*\t\tDEC/alpha\n");
fprintf(f,"trou\t\ta0a0ff\t\t.*AIX.*\t\t\tAIX\n");
fprintf(f,"triangle\tff0000\t\t.*Mozilla/3.0.*\t\tNS3 !!\n");
fprintf(f,"triangle\ta0a0ff\t\t.*Mozilla/4.7.*Win95.*\tNS4.7/w95\n");
fprintf(f,"triangle\ta0a0ff\t\t.*Mozilla/4.7.*Win98.*\tNS4.7/w98\n");
fprintf(f,"triangle\t50a0ff\t\t.*Mozilla/4.7.*WinNT.*\tNS4.7/NT4\n");
fprintf(f,"coin11\t\t0080ff\t\t.*Moz.*Win.*\t\tMoz-Win\n");
fprintf(f,"trianglebas\t808000\t\t.*[Ll]ynx.*\t\tLynx\n");
fprintf(f,"plus\t\t80ff80\t\t.*[Ll]inks.*\t\tLinks\n");
fprintf(f,"trianglebas\t00d0d0\t\t.*w3m.*\t\t\tw3m\n");
fprintf(f,"carre\t\ta0a000\t\t.*[Dd]illo.*\t\tDillo\n");
fprintf(f,"losange\t\tffff00\t\t.*[Pp]lop [Bb]ot.*\tPlop\n");
fprintf(f,"losange\t\t40d040\t\t.* [Bb]ot.*\t\tun bot!?\n");
fprintf(f,"carre\t\t1ce8ff\t\t.*\t\t\t?\n");
