/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_win (void);
GtkWidget* create_colorselectiondialog (void);
GtkWidget* create_fontselectiondialog (void);
GtkWidget* create_dialog_msg_ok (void);
GtkWidget* create_fileselection_save (void);
GtkWidget* create_fileselection_xpm (void);
