/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "wmccc_callbacks.h"
#include "wmccc_interface.h"
#include "wmccc_support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_win (void)
{
  GtkWidget *main_win;
  GtkWidget *vbox1;
  GtkWidget *hbox3;
  GtkWidget *vbox2;
  GtkWidget *scrolledwindow1;
  GtkWidget *sites_treeview;
  GtkWidget *image1;
  GtkWidget *statusbar1;

  main_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main_win), _("window1"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_win), vbox1);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox2, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  sites_treeview = gtk_tree_view_new ();
  gtk_widget_show (sites_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), sites_treeview);

  image1 = create_pixmap (main_win, "logo.xpm");
  gtk_widget_show (image1);
  gtk_box_pack_end (GTK_BOX (hbox3), image1, FALSE, FALSE, 0);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_win, main_win, "main_win");
  GLADE_HOOKUP_OBJECT (main_win, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_win, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (main_win, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_win, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (main_win, sites_treeview, "sites_treeview");
  GLADE_HOOKUP_OBJECT (main_win, image1, "image1");
  GLADE_HOOKUP_OBJECT (main_win, statusbar1, "statusbar1");

  return main_win;
}

GtkWidget*
create_messagebox_dialog (void)
{
  GtkWidget *messagebox_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *hbox5;
  GtkWidget *image2;
  GtkWidget *messagebox_label;
  GtkWidget *dialog_action_area1;
  GtkWidget *ok_button;

  messagebox_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (messagebox_dialog), _("Message from wmccc"));

  dialog_vbox1 = GTK_DIALOG (messagebox_dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), hbox5, TRUE, TRUE, 0);

  image2 = create_pixmap (messagebox_dialog, "badnews.xpm");
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox5), image2, FALSE, FALSE, 0);

  messagebox_label = gtk_label_new (_("plop"));
  gtk_widget_show (messagebox_label);
  gtk_box_pack_start (GTK_BOX (hbox5), messagebox_label, TRUE, TRUE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (messagebox_label), TRUE);
  gtk_misc_set_padding (GTK_MISC (messagebox_label), 7, 7);

  dialog_action_area1 = GTK_DIALOG (messagebox_dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (messagebox_dialog), ok_button, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_button, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) ok_button, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (messagebox_dialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (messagebox_dialog, messagebox_dialog, "messagebox_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (messagebox_dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (messagebox_dialog, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (messagebox_dialog, image2, "image2");
  GLADE_HOOKUP_OBJECT (messagebox_dialog, messagebox_label, "messagebox_label");
  GLADE_HOOKUP_OBJECT_NO_REF (messagebox_dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (messagebox_dialog, ok_button, "ok_button");

  return messagebox_dialog;
}

GtkWidget*
create_new_board_dialog (void)
{
  GtkWidget *new_board_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox3;
  GtkWidget *hbox13;
  GtkWidget *image4;
  GtkWidget *edit_bt;
  GtkWidget *alignment3;
  GtkWidget *hbox14;
  GtkWidget *image3;
  GtkWidget *label39;
  GtkWidget *vbox4;
  GtkWidget *frame1;
  GtkWidget *alignment2;
  GtkWidget *hbox4;
  GtkWidget *label37;
  GtkWidget *name;
  GtkWidget *label36;
  GtkWidget *pp_bgcolor_bt;
  GtkWidget *label6;
  GtkWidget *frame2;
  GtkWidget *table1;
  GtkWidget *label8;
  GtkWidget *backend_url;
  GtkWidget *label9;
  GtkWidget *backend_type;
  GtkWidget *menu1;
  GtkWidget *backend_type_1;
  GtkWidget *backend_type_2;
  GtkWidget *backend_type_3;
  GtkWidget *label10;
  GtkWidget *hscale_board_check_delay;
  GtkWidget *label7;
  GtkWidget *frame3;
  GtkWidget *alignment1;
  GtkWidget *table2;
  GtkWidget *label12;
  GtkWidget *path_board_add;
  GtkWidget *label13;
  GtkWidget *board_post;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport1;
  GtkWidget *cookies;
  GtkWidget *button1;
  GtkWidget *label14;
  GtkWidget *label11;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancel_bt;
  GtkWidget *apply_bt;
  GtkWidget *ok_bt;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  new_board_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (new_board_dialog), _("New board"));

  dialog_vbox2 = GTK_DIALOG (new_board_dialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox3, TRUE, TRUE, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox13, FALSE, FALSE, 0);

  image4 = create_pixmap (new_board_dialog, "logoh.png");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox13), image4, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (image4), 0, 0.5);

  edit_bt = gtk_button_new ();
  gtk_widget_show (edit_bt);
  gtk_box_pack_start (GTK_BOX (hbox13), edit_bt, TRUE, TRUE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (edit_bt), alignment3);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox14);

  image3 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox14), image3, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Click here to edit the options file"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox14), label39, FALSE, FALSE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox4), frame1, TRUE, TRUE, 2);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame1), alignment2);

  hbox4 = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox4);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 2);

  label37 = gtk_label_new (_("Give a (short) name for the board:"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox4), label37, FALSE, FALSE, 0);

  name = gtk_entry_new ();
  gtk_widget_show (name);
  gtk_box_pack_start (GTK_BOX (hbox4), name, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, name, _("Try to be short"), NULL);
  gtk_entry_set_text (GTK_ENTRY (name), _("dlfp"));

  label36 = gtk_label_new (_("Background color: "));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox4), label36, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label36), 1, 0.5);

  pp_bgcolor_bt = gtk_button_new_with_mnemonic (_("pp_bgcolor_bt"));
  gtk_widget_show (pp_bgcolor_bt);
  gtk_box_pack_start (GTK_BOX (hbox4), pp_bgcolor_bt, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, pp_bgcolor_bt, _("You can customize the background color of the messages for this new site"), NULL);

  label6 = gtk_label_new (_("Basic settings"));
  gtk_widget_show (label6);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label6);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox4), frame2, TRUE, TRUE, 2);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame2), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 2);

  label8 = gtk_label_new (_("Backend URL:"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  backend_url = gtk_entry_new ();
  gtk_widget_show (backend_url);
  gtk_table_attach (GTK_TABLE (table1), backend_url, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (backend_url, 500, -1);
  gtk_entry_set_text (GTK_ENTRY (backend_url), _("http://linuxfr.org/board/backend.xml"));

  label9 = gtk_label_new (_("Backend type:"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  backend_type = gtk_option_menu_new ();
  gtk_widget_show (backend_type);
  gtk_table_attach (GTK_TABLE (table1), backend_type, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  menu1 = gtk_menu_new ();

  backend_type_1 = gtk_menu_item_new_with_mnemonic (_("message tags are \"htmlentitised\""));
  gtk_widget_show (backend_type_1);
  gtk_container_add (GTK_CONTAINER (menu1), backend_type_1);

  backend_type_2 = gtk_menu_item_new_with_mnemonic (_("message tags are raw"));
  gtk_widget_show (backend_type_2);
  gtk_container_add (GTK_CONTAINER (menu1), backend_type_2);

  backend_type_3 = gtk_menu_item_new_with_mnemonic (_("the backend has no pants"));
  gtk_widget_show (backend_type_3);
  gtk_container_add (GTK_CONTAINER (menu1), backend_type_3);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (backend_type), menu1);

  label10 = gtk_label_new (_("Refresh frequency\n (seconds): "));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table1), label10, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  hscale_board_check_delay = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (50.3, 10, 300, 1, 1, 0)));
  gtk_widget_show (hscale_board_check_delay);
  gtk_table_attach (GTK_TABLE (table1), hscale_board_check_delay, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_range_set_update_policy (GTK_RANGE (hscale_board_check_delay), GTK_UPDATE_DISCONTINUOUS);

  label7 = gtk_label_new (_("XML Backend information"));
  gtk_widget_show (label7);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label7);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox4), frame3, TRUE, TRUE, 2);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame3), alignment1);

  table2 = gtk_table_new (3, 3, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (alignment1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 2);

  label12 = gtk_label_new (_("Post URL:"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  path_board_add = gtk_entry_new ();
  gtk_widget_show (path_board_add);
  gtk_table_attach (GTK_TABLE (table2), path_board_add, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label13 = gtk_label_new (_("Specific:"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  board_post = gtk_entry_new ();
  gtk_widget_show (board_post);
  gtk_table_attach (GTK_TABLE (table2), board_post, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_table_attach (GTK_TABLE (table2), scrolledwindow2, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);

  cookies = gtk_entry_new ();
  gtk_widget_show (cookies);
  gtk_container_add (GTK_CONTAINER (viewport1), cookies);

  button1 = gtk_button_new_with_mnemonic (_("(grab cookie)"));
  gtk_widget_show (button1);
  gtk_table_attach (GTK_TABLE (table2), button1, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, button1, _("attempt to get the cookie from the cookies stored in your browsers"), NULL);

  label14 = gtk_label_new (_("Cookie"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label11 = gtk_label_new (_("Sending messages to the board"));
  gtk_widget_show (label11);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label11);

  dialog_action_area2 = GTK_DIALOG (new_board_dialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancel_bt = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (new_board_dialog), cancel_bt, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_bt, GTK_CAN_DEFAULT);

  apply_bt = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (new_board_dialog), apply_bt, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (apply_bt, GTK_CAN_DEFAULT);

  ok_bt = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (new_board_dialog), ok_bt, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_bt, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) edit_bt, "clicked",
                    G_CALLBACK (edit_bt_clicked),
                    NULL);
  g_signal_connect ((gpointer) backend_type_1, "activate",
                    G_CALLBACK (on_message_tags_are__htmlentitised_1_activate),
                    NULL);
  g_signal_connect ((gpointer) backend_type_2, "activate",
                    G_CALLBACK (on_message_tags_are_raw1_activate),
                    NULL);
  g_signal_connect ((gpointer) backend_type_3, "activate",
                    G_CALLBACK (on_the_backend_has_no_pants1_activate),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancel_bt, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (new_board_dialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (new_board_dialog, new_board_dialog, "new_board_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (new_board_dialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (new_board_dialog, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (new_board_dialog, image4, "image4");
  GLADE_HOOKUP_OBJECT (new_board_dialog, edit_bt, "edit_bt");
  GLADE_HOOKUP_OBJECT (new_board_dialog, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (new_board_dialog, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (new_board_dialog, image3, "image3");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label39, "label39");
  GLADE_HOOKUP_OBJECT (new_board_dialog, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (new_board_dialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label37, "label37");
  GLADE_HOOKUP_OBJECT (new_board_dialog, name, "name");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label36, "label36");
  GLADE_HOOKUP_OBJECT (new_board_dialog, pp_bgcolor_bt, "pp_bgcolor_bt");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label6, "label6");
  GLADE_HOOKUP_OBJECT (new_board_dialog, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label8, "label8");
  GLADE_HOOKUP_OBJECT (new_board_dialog, backend_url, "backend_url");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label9, "label9");
  GLADE_HOOKUP_OBJECT (new_board_dialog, backend_type, "backend_type");
  GLADE_HOOKUP_OBJECT (new_board_dialog, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, backend_type_1, "backend_type_1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, backend_type_2, "backend_type_2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, backend_type_3, "backend_type_3");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label10, "label10");
  GLADE_HOOKUP_OBJECT (new_board_dialog, hscale_board_check_delay, "hscale_board_check_delay");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label7, "label7");
  GLADE_HOOKUP_OBJECT (new_board_dialog, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (new_board_dialog, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, table2, "table2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label12, "label12");
  GLADE_HOOKUP_OBJECT (new_board_dialog, path_board_add, "path_board_add");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label13, "label13");
  GLADE_HOOKUP_OBJECT (new_board_dialog, board_post, "board_post");
  GLADE_HOOKUP_OBJECT (new_board_dialog, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, cookies, "cookies");
  GLADE_HOOKUP_OBJECT (new_board_dialog, button1, "button1");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label14, "label14");
  GLADE_HOOKUP_OBJECT (new_board_dialog, label11, "label11");
  GLADE_HOOKUP_OBJECT_NO_REF (new_board_dialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (new_board_dialog, cancel_bt, "cancel_bt");
  GLADE_HOOKUP_OBJECT (new_board_dialog, apply_bt, "apply_bt");
  GLADE_HOOKUP_OBJECT (new_board_dialog, ok_bt, "ok_bt");
  GLADE_HOOKUP_OBJECT_NO_REF (new_board_dialog, tooltips, "tooltips");

  return new_board_dialog;
}

GtkWidget*
create_colorselection_dialog (void)
{
  GtkWidget *colorselection_dialog;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;
  GtkWidget *help_button1;
  GtkWidget *color_selection1;

  colorselection_dialog = gtk_color_selection_dialog_new (_("Choix de la couleur"));
  gtk_window_set_resizable (GTK_WINDOW (colorselection_dialog), FALSE);

  ok_button1 = GTK_COLOR_SELECTION_DIALOG (colorselection_dialog)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_COLOR_SELECTION_DIALOG (colorselection_dialog)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  help_button1 = GTK_COLOR_SELECTION_DIALOG (colorselection_dialog)->help_button;
  gtk_widget_show (help_button1);
  GTK_WIDGET_SET_FLAGS (help_button1, GTK_CAN_DEFAULT);

  color_selection1 = GTK_COLOR_SELECTION_DIALOG (colorselection_dialog)->colorsel;
  gtk_widget_show (color_selection1);
  gtk_color_selection_set_has_opacity_control (GTK_COLOR_SELECTION (color_selection1), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (colorselection_dialog, colorselection_dialog, "colorselection_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (colorselection_dialog, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (colorselection_dialog, cancel_button1, "cancel_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (colorselection_dialog, help_button1, "help_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (colorselection_dialog, color_selection1, "color_selection1");

  return colorselection_dialog;
}

GtkWidget*
create_pinnipede_dialog (void)
{
  GtkWidget *pinnipede_dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *vbox5;
  GtkWidget *label15;
  GtkWidget *frame4;
  GtkWidget *vbox6;
  GtkWidget *frame6;
  GtkWidget *hbox6;
  GtkWidget *label19;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *fnfamily_comboentry;
  GtkWidget *label20;
  GtkObject *fnsize_spinbutton_adj;
  GtkWidget *fnsize_spinbutton;
  GtkWidget *label18;
  GtkWidget *hbox9;
  GtkWidget *pp_auto_open;
  GtkWidget *pp_auto_open_fb;
  GtkWidget *hbox10;
  GtkWidget *pp_use_classical_tabs;
  GtkWidget *pp_use_classical_tabs_fb;
  GtkWidget *hbox11;
  GtkWidget *pp_use_colored_tabs;
  GtkWidget *pp_use_colored_tabs_fb;
  GtkWidget *hbox12;
  GtkWidget *pp_hungry_boitakon;
  GtkWidget *pp_hungry_boitakon_fb;
  GtkWidget *hbox18;
  GtkWidget *disable_aa;
  GtkWidget *disable_aa_fb;
  GtkWidget *label16;
  GtkWidget *frame5;
  GtkWidget *vbox7;
  GtkWidget *hboxlkjjkl;
  GtkWidget *mark_id_gaps_checkbutton;
  GtkWidget *mark_id_gaps_checkbutton_fb;
  GtkWidget *frame7;
  GtkWidget *table3;
  GtkWidget *bt_pp_bgcolor_fb;
  GtkWidget *pp_bgcolor_bt;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *pp_fgcolor_bt;
  GtkWidget *pp_trollscore_color_bt;
  GtkWidget *pp_login_color_bt;
  GtkWidget *pp_useragent_color_bt;
  GtkWidget *pp_tstamp_color_bt;
  GtkWidget *pp_url_color_bt;
  GtkWidget *pp_visited_url_color_bt;
  GtkWidget *label23;
  GtkWidget *label17;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancel_bt;
  GtkWidget *apply_bt;
  GtkWidget *ok_bt;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  pinnipede_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (pinnipede_dialog), _("Change pinnipede settings"));

  dialog_vbox3 = GTK_DIALOG (pinnipede_dialog)->vbox;
  gtk_widget_show (dialog_vbox3);

  vbox5 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vbox5, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("Change pinnipede options"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (vbox5), label15, FALSE, FALSE, 0);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox5), frame4, TRUE, TRUE, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (frame4), vbox6);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox6), frame6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 2);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (frame6), hbox6);

  label19 = gtk_label_new (_("Font family"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox6), label19, FALSE, FALSE, 0);

  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox6), combo1, TRUE, TRUE, 0);
  combo1_items = g_list_append (combo1_items, (gpointer) _("helvetica"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("verdana"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("courier"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("fixed"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("arial"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  fnfamily_comboentry = GTK_COMBO (combo1)->entry;
  gtk_widget_show (fnfamily_comboentry);

  label20 = gtk_label_new (_("Font size"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox6), label20, FALSE, FALSE, 0);

  fnsize_spinbutton_adj = gtk_adjustment_new (2, 0, 100, 1, 10, 10);
  fnsize_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (fnsize_spinbutton_adj), 1, 0);
  gtk_widget_show (fnsize_spinbutton);
  gtk_box_pack_start (GTK_BOX (hbox6), fnsize_spinbutton, TRUE, TRUE, 0);

  label18 = gtk_label_new (_("Font"));
  gtk_widget_show (label18);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label18);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox9, FALSE, FALSE, 0);

  pp_auto_open = gtk_check_button_new_with_mnemonic (_("Auto-open on startup"));
  gtk_widget_show (pp_auto_open);
  gtk_box_pack_start (GTK_BOX (hbox9), pp_auto_open, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, pp_auto_open, _("The pinnipede window will show up as soon as wmcoincoin is started"), NULL);

  pp_auto_open_fb = gtk_label_new (_("label32"));
  gtk_widget_show (pp_auto_open_fb);
  gtk_box_pack_start (GTK_BOX (hbox9), pp_auto_open_fb, FALSE, FALSE, 0);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox10, TRUE, TRUE, 0);

  pp_use_classical_tabs = gtk_check_button_new_with_mnemonic (_("Use 'classical' tabs behaviour"));
  gtk_widget_show (pp_use_classical_tabs);
  gtk_box_pack_start (GTK_BOX (hbox10), pp_use_classical_tabs, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, pp_use_classical_tabs, _("if you think that the default behaviour of the tabs sucks.."), NULL);

  pp_use_classical_tabs_fb = gtk_label_new (_("label32"));
  gtk_widget_show (pp_use_classical_tabs_fb);
  gtk_box_pack_start (GTK_BOX (hbox10), pp_use_classical_tabs_fb, FALSE, FALSE, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox11, TRUE, TRUE, 0);

  pp_use_colored_tabs = gtk_check_button_new_with_mnemonic (_("Colored tabs"));
  gtk_widget_show (pp_use_colored_tabs);
  gtk_box_pack_start (GTK_BOX (hbox11), pp_use_colored_tabs, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, pp_use_colored_tabs, _("if used, the \"tabs\" will be colored accordingly to the background color of the messages in the pinnipede"), NULL);

  pp_use_colored_tabs_fb = gtk_label_new (_("label32"));
  gtk_widget_show (pp_use_colored_tabs_fb);
  gtk_box_pack_start (GTK_BOX (hbox11), pp_use_colored_tabs_fb, FALSE, FALSE, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox12, TRUE, TRUE, 0);

  pp_hungry_boitakon = gtk_check_button_new_with_mnemonic (_("Very Hungry boitakon"));
  gtk_widget_show (pp_hungry_boitakon);
  gtk_box_pack_start (GTK_BOX (hbox12), pp_hungry_boitakon, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, pp_hungry_boitakon, _("If a message replies to a message in the hungry boitakon and another one which is not in the boitakon, it will be put in the boitakon only if this option is toggled"), NULL);

  pp_hungry_boitakon_fb = gtk_label_new (_("label32"));
  gtk_widget_show (pp_hungry_boitakon_fb);
  gtk_box_pack_start (GTK_BOX (hbox12), pp_hungry_boitakon_fb, FALSE, FALSE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox18, TRUE, TRUE, 0);

  disable_aa = gtk_check_button_new_with_mnemonic (_("Disable antialiasing"));
  gtk_widget_show (disable_aa);
  gtk_box_pack_start (GTK_BOX (hbox18), disable_aa, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, disable_aa, _("If a message replies to a message in the hungry boitakon and another one which is not in the boitakon, it will be put in the boitakon only if this option is toggled"), NULL);

  disable_aa_fb = gtk_label_new (_("label32"));
  gtk_widget_show (disable_aa_fb);
  gtk_box_pack_start (GTK_BOX (hbox18), disable_aa_fb, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Global settings"));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label16);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox5), frame5, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (frame5), vbox7);

  hboxlkjjkl = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hboxlkjjkl);
  gtk_box_pack_start (GTK_BOX (vbox7), hboxlkjjkl, FALSE, FALSE, 0);

  mark_id_gaps_checkbutton = gtk_check_button_new_with_mnemonic (_("View id gaps (red dotted line)"));
  gtk_widget_show (mark_id_gaps_checkbutton);
  gtk_box_pack_start (GTK_BOX (hboxlkjjkl), mark_id_gaps_checkbutton, FALSE, FALSE, 0);

  mark_id_gaps_checkbutton_fb = gtk_label_new (_("xx"));
  gtk_widget_show (mark_id_gaps_checkbutton_fb);
  gtk_box_pack_start (GTK_BOX (hboxlkjjkl), mark_id_gaps_checkbutton_fb, FALSE, FALSE, 0);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (vbox7), frame7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame7), 2);

  table3 = gtk_table_new (3, 6, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame7), table3);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  bt_pp_bgcolor_fb = gtk_label_new (_("Background color"));
  gtk_widget_show (bt_pp_bgcolor_fb);
  gtk_table_attach (GTK_TABLE (table3), bt_pp_bgcolor_fb, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (bt_pp_bgcolor_fb), 0, 0.5);

  pp_bgcolor_bt = gtk_button_new_with_mnemonic (_("pp_bgcolor_bt"));
  gtk_widget_show (pp_bgcolor_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_bgcolor_bt, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label25 = gtk_label_new (_("Text foreground"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table3), label25, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label26 = gtk_label_new (_("Logins"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table3), label26, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Useragents"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Urls"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table3), label28, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Visited Urls"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table3), label29, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Clocks"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table3), label30, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label31 = gtk_label_new (_("Troll score"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table3), label31, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  pp_fgcolor_bt = gtk_button_new_with_mnemonic (_("button4"));
  gtk_widget_show (pp_fgcolor_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_fgcolor_bt, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pp_trollscore_color_bt = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (pp_trollscore_color_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_trollscore_color_bt, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pp_login_color_bt = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (pp_login_color_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_login_color_bt, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pp_useragent_color_bt = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (pp_useragent_color_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_useragent_color_bt, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pp_tstamp_color_bt = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (pp_tstamp_color_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_tstamp_color_bt, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pp_url_color_bt = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (pp_url_color_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_url_color_bt, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  pp_visited_url_color_bt = gtk_button_new_with_mnemonic (_("button5"));
  gtk_widget_show (pp_visited_url_color_bt);
  gtk_table_attach (GTK_TABLE (table3), pp_visited_url_color_bt, 5, 6, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label23 = gtk_label_new (_("Various colors"));
  gtk_widget_show (label23);
  gtk_frame_set_label_widget (GTK_FRAME (frame7), label23);

  label17 = gtk_label_new (_("Settings applied to sites"));
  gtk_widget_show (label17);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label17);

  dialog_action_area3 = GTK_DIALOG (pinnipede_dialog)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancel_bt = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (pinnipede_dialog), cancel_bt, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_bt, GTK_CAN_DEFAULT);

  apply_bt = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (pinnipede_dialog), apply_bt, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (apply_bt, GTK_CAN_DEFAULT);

  ok_bt = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (pinnipede_dialog), ok_bt, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_bt, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) mark_id_gaps_checkbutton, "toggled",
                    G_CALLBACK (on_mark_id_gaps_checkbutton_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancel_bt, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (pinnipede_dialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pinnipede_dialog, pinnipede_dialog, "pinnipede_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (pinnipede_dialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label15, "label15");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label19, "label19");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, fnfamily_comboentry, "fnfamily_comboentry");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label20, "label20");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, fnsize_spinbutton, "fnsize_spinbutton");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label18, "label18");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_auto_open, "pp_auto_open");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_auto_open_fb, "pp_auto_open_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_use_classical_tabs, "pp_use_classical_tabs");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_use_classical_tabs_fb, "pp_use_classical_tabs_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_use_colored_tabs, "pp_use_colored_tabs");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_use_colored_tabs_fb, "pp_use_colored_tabs_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_hungry_boitakon, "pp_hungry_boitakon");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_hungry_boitakon_fb, "pp_hungry_boitakon_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, disable_aa, "disable_aa");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, disable_aa_fb, "disable_aa_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label16, "label16");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, hboxlkjjkl, "hboxlkjjkl");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, mark_id_gaps_checkbutton, "mark_id_gaps_checkbutton");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, mark_id_gaps_checkbutton_fb, "mark_id_gaps_checkbutton_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, table3, "table3");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, bt_pp_bgcolor_fb, "bt_pp_bgcolor_fb");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_bgcolor_bt, "pp_bgcolor_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label25, "label25");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label26, "label26");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label27, "label27");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label28, "label28");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label29, "label29");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label30, "label30");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label31, "label31");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_fgcolor_bt, "pp_fgcolor_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_trollscore_color_bt, "pp_trollscore_color_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_login_color_bt, "pp_login_color_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_useragent_color_bt, "pp_useragent_color_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_tstamp_color_bt, "pp_tstamp_color_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_url_color_bt, "pp_url_color_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, pp_visited_url_color_bt, "pp_visited_url_color_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label23, "label23");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, label17, "label17");
  GLADE_HOOKUP_OBJECT_NO_REF (pinnipede_dialog, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, cancel_bt, "cancel_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, apply_bt, "apply_bt");
  GLADE_HOOKUP_OBJECT (pinnipede_dialog, ok_bt, "ok_bt");
  GLADE_HOOKUP_OBJECT_NO_REF (pinnipede_dialog, tooltips, "tooltips");

  return pinnipede_dialog;
}

GtkWidget*
create_edit_dialog (void)
{
  GtkWidget *edit_dialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox8;
  GtkWidget *label38;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview;
  GtkWidget *dialog_action_area4;
  GtkWidget *cancel_bt;
  GtkWidget *apply_bt;
  GtkWidget *ok_bt;

  edit_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (edit_dialog), _("Options edit"));
  gtk_window_set_modal (GTK_WINDOW (edit_dialog), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (edit_dialog), 600, 450);

  dialog_vbox4 = GTK_DIALOG (edit_dialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox8, TRUE, TRUE, 0);

  label38 = gtk_label_new (_("wmccc \"do it yourself\" flavor"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (vbox8), label38, FALSE, FALSE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  textview = gtk_text_view_new ();
  gtk_widget_show (textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview);

  dialog_action_area4 = GTK_DIALOG (edit_dialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  cancel_bt = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (edit_dialog), cancel_bt, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_bt, GTK_CAN_DEFAULT);

  apply_bt = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (edit_dialog), apply_bt, GTK_RESPONSE_APPLY);
  GTK_WIDGET_SET_FLAGS (apply_bt, GTK_CAN_DEFAULT);

  ok_bt = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok_bt);
  gtk_dialog_add_action_widget (GTK_DIALOG (edit_dialog), ok_bt, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_bt, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (edit_dialog, edit_dialog, "edit_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (edit_dialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (edit_dialog, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (edit_dialog, label38, "label38");
  GLADE_HOOKUP_OBJECT (edit_dialog, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (edit_dialog, textview, "textview");
  GLADE_HOOKUP_OBJECT_NO_REF (edit_dialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (edit_dialog, cancel_bt, "cancel_bt");
  GLADE_HOOKUP_OBJECT (edit_dialog, apply_bt, "apply_bt");
  GLADE_HOOKUP_OBJECT (edit_dialog, ok_bt, "ok_bt");

  return edit_dialog;
}

GtkWidget*
create_bronson_wizard (void)
{
  GtkWidget *bronson_wizard;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox9;
  GtkWidget *hbox15;
  GtkWidget *image5;
  GtkWidget *label40;
  GtkWidget *hseparator1;
  GtkWidget *hbox16;
  GtkWidget *label41;
  GtkWidget *vbox11;
  GtkWidget *wizard_new_board_bt;
  GtkWidget *wizard_new_feed_bt;
  GtkWidget *wizard_edit_options_bt;
  GtkWidget *dialog_action_area5;
  GtkWidget *button2;

  bronson_wizard = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (bronson_wizard), _("the wmccc wizard"));

  dialog_vbox5 = GTK_DIALOG (bronson_wizard)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox9, TRUE, TRUE, 0);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox15, FALSE, TRUE, 0);

  image5 = create_pixmap (bronson_wizard, "cbronson.jpg");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox15), image5, FALSE, FALSE, 0);

  label40 = gtk_label_new (_("Hello, I am Charles Bronson and I am going to guide you during the configuration of wmcoincoin.\nDon't fuck with me or I'll kick your ass with a mammoth's cubitus"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox15), label40, FALSE, FALSE, 8);
  gtk_label_set_line_wrap (GTK_LABEL (label40), TRUE);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox9), hseparator1, TRUE, TRUE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox16, TRUE, TRUE, 0);

  label41 = gtk_label_new (_("Where do you want to go today ?"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox16), label41, TRUE, FALSE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox16), vbox11, FALSE, FALSE, 23);

  wizard_new_board_bt = gtk_button_new_with_mnemonic (_("I want to add a new board"));
  gtk_widget_show (wizard_new_board_bt);
  gtk_box_pack_start (GTK_BOX (vbox11), wizard_new_board_bt, FALSE, FALSE, 0);

  wizard_new_feed_bt = gtk_button_new_with_mnemonic (_("I want to add a new RSS feed"));
  gtk_widget_show (wizard_new_feed_bt);
  gtk_box_pack_start (GTK_BOX (vbox11), wizard_new_feed_bt, FALSE, FALSE, 0);

  wizard_edit_options_bt = gtk_button_new_with_mnemonic (_("I want to edit the options"));
  gtk_widget_show (wizard_edit_options_bt);
  gtk_box_pack_start (GTK_BOX (vbox11), wizard_edit_options_bt, FALSE, FALSE, 0);

  dialog_action_area5 = GTK_DIALOG (bronson_wizard)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (bronson_wizard), button2, 0);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bronson_wizard, bronson_wizard, "bronson_wizard");
  GLADE_HOOKUP_OBJECT_NO_REF (bronson_wizard, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (bronson_wizard, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (bronson_wizard, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (bronson_wizard, image5, "image5");
  GLADE_HOOKUP_OBJECT (bronson_wizard, label40, "label40");
  GLADE_HOOKUP_OBJECT (bronson_wizard, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (bronson_wizard, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (bronson_wizard, label41, "label41");
  GLADE_HOOKUP_OBJECT (bronson_wizard, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (bronson_wizard, wizard_new_board_bt, "wizard_new_board_bt");
  GLADE_HOOKUP_OBJECT (bronson_wizard, wizard_new_feed_bt, "wizard_new_feed_bt");
  GLADE_HOOKUP_OBJECT (bronson_wizard, wizard_edit_options_bt, "wizard_edit_options_bt");
  GLADE_HOOKUP_OBJECT_NO_REF (bronson_wizard, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (bronson_wizard, button2, "button2");

  return bronson_wizard;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");

  return window1;
}

GtkWidget*
create_sitelist_dialog (void)
{
  GtkWidget *sitelist_dialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *vbox12;
  GtkWidget *hseparator2;
  GtkWidget *hbox17;
  GtkWidget *vseparator2;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview;
  GtkWidget *vseparator1;
  GtkWidget *vbox13;
  GtkWidget *edit_bt;
  GtkWidget *remove_bt;
  GtkWidget *button8;
  GtkWidget *hseparator3;
  GtkWidget *dialog_action_area7;
  GtkWidget *closebutton1;

  sitelist_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (sitelist_dialog), _("dialog2"));
  gtk_window_set_default_size (GTK_WINDOW (sitelist_dialog), 640, 460);

  dialog_vbox7 = GTK_DIALOG (sitelist_dialog)->vbox;
  gtk_widget_show (dialog_vbox7);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), vbox12, TRUE, TRUE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox12), hseparator2, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox17, TRUE, TRUE, 0);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_box_pack_start (GTK_BOX (hbox17), vseparator2, FALSE, FALSE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox17), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox17), vseparator1, FALSE, FALSE, 0);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox17), vbox13, FALSE, FALSE, 0);

  edit_bt = gtk_button_new_with_mnemonic (_("edit the selected sites"));
  gtk_widget_show (edit_bt);
  gtk_box_pack_start (GTK_BOX (vbox13), edit_bt, FALSE, FALSE, 0);

  remove_bt = gtk_button_new_with_mnemonic (_("remove the selected sites"));
  gtk_widget_show (remove_bt);
  gtk_box_pack_start (GTK_BOX (vbox13), remove_bt, FALSE, FALSE, 0);

  button8 = gtk_button_new_with_mnemonic (_("New site"));
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (vbox13), button8, FALSE, FALSE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox12), hseparator3, FALSE, FALSE, 0);

  dialog_action_area7 = GTK_DIALOG (sitelist_dialog)->action_area;
  gtk_widget_show (dialog_action_area7);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area7), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (sitelist_dialog), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (sitelist_dialog, sitelist_dialog, "sitelist_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (sitelist_dialog, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, edit_bt, "edit_bt");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, remove_bt, "remove_bt");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, button8, "button8");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT_NO_REF (sitelist_dialog, dialog_action_area7, "dialog_action_area7");
  GLADE_HOOKUP_OBJECT (sitelist_dialog, closebutton1, "closebutton1");

  return sitelist_dialog;
}

