/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_win (void);
GtkWidget* create_messagebox_dialog (void);
GtkWidget* create_new_board_dialog (void);
GtkWidget* create_colorselection_dialog (void);
GtkWidget* create_pinnipede_dialog (void);
GtkWidget* create_edit_dialog (void);
GtkWidget* create_bronson_wizard (void);
